CONDITIONS = {
    "Afraid": "Fearful and anxious",
    "Angry": "Filled with rage",
    "Anxious": "Uneasy and worried",
    "Battered": "Beaten and bruised",
    "Bitten": "Bitten by something",
    "Beaten": "Physically beaten up",
    "Bleeding": "Blood oozing from wounds",
    "Bloodied": "Covered in blood",
    "Bludgeoned": "Hit with blunt force",
    "Broken bones": "Fractured bones",
    "Bruised": "Covered in bruises",
    "Burned": "Injured by fire or heat",
    "Cold": "Chilled to the bone",
    "Concussed": "Suffering from a concussion",
    "Confused": "Mentally disoriented",
    "Coughing": "Persistent coughing",
    "Cursed": "Hexed or cursed",
    "Cut": "Wounded by a sharp object",
    "Decayed": "Rotting and decaying",
    "Depressed": "Feeling deep sadness",
    "Distracted": "Easily diverted attention",
    "Distraught": "Overwhelmed with emotion",
    "Drained": "Lacking energy or vitality",
    "Exhausted": "Physically and mentally tired",
    "Feverish": "Having a high temperature",
    "Frail": "Physically weak and delicate",
    "Frozen": "Stiff and immobilized",
    "Furious": "Enraged and furious",
    "Gaunt": "Emaciated and thin",
    "Grazed": "Skin scraped and wounded",
    "Haunted": "Tormented by spirits",
    "Heartbroken": "Deeply saddened",
    "Horrified": "Filled with horror",
    "Ill": "Physically unwell",
    "Impaled": "Pierced by an object",
    "Infected": "Infection in wounds",
    "Injured": "Physically hurt",
    "Jealous": "Envious and resentful",
    "Jolted": "Sudden shock or impact",
    "Jumpy": "Easily startled",
    "Lacerated": "Torn and cut",
    "Lost": "Confused and directionless",
    "Mad": "Insane and irrational",
    "Mauled": "Brutally attacked",
    "Miserable": "Extremely unhappy",
    "Nailed": "Nails driven into flesh",
    "Necrotic flesh": "Flesh decaying and necrotic",
    "Nihilistic": "Believing life is meaningless",
    "Obsessed": "Fixated on something",
    "Pale": "Unusually pale skin",
    "Panicked": "Filled with panic",
    "Paranoid": "Suspicious and distrustful",
    "Poisoned": "Exposed to toxins",
    "Possessed": "Controlled by a malevolent entity",
    "Relentless": "Determined and unyielding",
    "Scared": "Feeling fear",
    "Seduced": "Influenced by seduction",
    "Shaken": "Shaken and disturbed",
    "Shot": "Injured by a projectile",
    "Sick": "Physically unwell",
    "Slashed": "Cut deeply by a sharp object",
    "Sliced": "Cut in thin, clean lines",
    "Sore": "Aching and uncomfortable",
    "Stabbed": "Wounded by stabbing",
    "Stiff": "Stiff and immobile",
    "Strangled": "Choked and unable to breathe",
    "Terrified": "Filled with extreme fear",
    "Traumatized": "Suffering from emotional trauma",
    "Uneasy": "Feeling uneasy",
    "Unsettled": "Not at ease",
    "Unstable": "Lacking stability",
    "Upset": "Emotionally distressed",
    "Vicious": "Brutal and aggressive",
    "Weakened": "Physically weakened",
    "Worried": "Anxious and concerned",
    "Wounded": "Physically hurt",
}
