SKILLS = {
    "ACROBATICS": "Tumbling, jumping, leaping",
    "AIM": "Take careful appraisal of your target",
    "ALCHEMY": "Brewing, ingredients, potions",
    "ASSASSINATION": "Quiet and subtle murder",
    "ATHLETICS": "Lifting, swimming, climbing",
    "ARCANA": "The art of diabolic magic",
    "BRAWL": "Fighting close and dirty",
    "COMMAND": "Order and lead people",
    "CONSORT": "Polite conversation",
    "DECEPTION": "Lying, swaying, bullshit",
    "DEMONOLOGY": "Knowing demons",
    "DUEL": "One-on-one combat with people",
    "ENDURANCE": "Physical constitution",
    "EXPLOSIVES": "Using bombs, etc",
    "GROVEL": "Beg and plead",
    "HISTORY": "Knowing old important things",
    "HUNT": "Stalking and tracking a target",
    "HUSBANDRY": "Knowing animals",
    "INTIMIDATION": "Getting what you want",
    "INVENT": "Making tools with what you have",
    "MANOEUVRE": "Moving cleverly",
    "MEDICINE": "Healing yourself and others",
    "MURDER": "Killing people",
    "NAVIGATION": "Finding your way around",
    "PERSUASION": "Convincing people",
    "POISONS": "Deadly concoctions and herbs",
    "PRAY": "Ask for help or forgiveness",
    "REASON": "Find clues, think carefully",
    "RHETORIC": "Fine and tricky words",
    "RITUALS": "Sigils and magic circles",
    "SCAVENGE": "Picking through detritus",
    "SCRAMBLE": "Moving quickly out of danger",
    "SHOOT": "Ranged attacks",
    "TINKER": "Picking locks, disarming traps",
    "TOIL": "Shovelling, clearing rubble, drudgery",
    "SNEAK": "Skulking in the shadows",
    "STUDY": "Closely inspecting things",
    "SURVEY": "Carefully watch people and places",
    "TACTICS": "Planning, flanking, etc.",
    "WRECK": "Breaking and destroying obstacles"
}
